import os

#密钥
CSRF_ENABLED = True
SECRET_KEY = os.urandom(25)


SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:123456@localhost:3306/HUAWEI'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_COMMIT_TEARDOWN = True
SQLALCHEMY_COMMIT_ON_TEARDOWN = True