"""'version3.1'

Revision ID: c49a42d42c68
Revises: 
Create Date: 2018-10-06 17:33:05.334238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c49a42d42c68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cus_shop_ibfk_2', 'cus_shop', type_='foreignkey')
    op.create_foreign_key(None, 'cus_shop', 'shoppingcar', ['uid'], ['id'])
    op.drop_column('goods', 'bettery')
    op.drop_column('goods', 'storage')
    op.add_column('shoppingcar', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('shoppingcar', 'uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shoppingcar', 'uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('shoppingcar', 'id')
    op.add_column('goods', sa.Column('storage', mysql.INTEGER(display_width=5), autoincrement=False, nullable=True))
    op.add_column('goods', sa.Column('bettery', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cus_shop', type_='foreignkey')
    op.create_foreign_key('cus_shop_ibfk_2', 'cus_shop', 'shoppingcar', ['uid'], ['uid'])
    # ### end Alembic commands ###
